language: ruby
cache: bundler
sudo: required
before_install:
        - sudo update-ca-certificates
install:
        - bundle install
        - bundle exec rake build:production
script: bundle exec rake test
